-- =============================================
-- EPCO - Seed: 20 tickets por cada estado (120 total)
-- Estados: abierto, asignado, en_proceso, pendiente, resuelto, cerrado
-- =============================================

USE epco;

-- Limpiar tickets y datos relacionados existentes
DELETE FROM ticket_comments;
DELETE FROM ticket_history;
DELETE FROM ticket_attachments;
DELETE FROM tickets;

-- Reiniciar auto-increment
ALTER TABLE tickets AUTO_INCREMENT = 1;
ALTER TABLE ticket_comments AUTO_INCREMENT = 1;
ALTER TABLE ticket_history AUTO_INCREMENT = 1;

-- =============================================
-- ESTADO: ABIERTO (20 tickets)
-- =============================================
INSERT INTO tickets (ticket_number, user_id, user_name, user_email, user_department, category, priority, title, description, status, sla_response_target, sla_resolution_target, created_at) VALUES
('TK-2026-0001', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'software', 'media', 'Excel se cierra inesperadamente', 'Al abrir archivos grandes en Excel, la aplicación se cierra sin previo aviso. El problema comenzó tras la última actualización.', 'abierto', 120, 1440, DATE_SUB(NOW(), INTERVAL 1 HOUR)),
('TK-2026-0002', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'hardware', 'alta', 'Teclado no responde', 'Mi teclado dejó de funcionar esta mañana. Cambié las pilas y probé en otro puerto USB sin resultado.', 'abierto', 60, 480, DATE_SUB(NOW(), INTERVAL 2 HOUR)),
('TK-2026-0003', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'red', 'urgente', 'Sin acceso a internet en Operaciones', 'Todo el piso de Operaciones perdió conexión a internet desde las 8:00 AM. Afecta a 15 personas.', 'abierto', 30, 240, DATE_SUB(NOW(), INTERVAL 30 MINUTE)),
('TK-2026-0004', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'acceso', 'media', 'Solicitud de acceso a SAP FI', 'Necesito acceso al módulo financiero de SAP para generar reportes de cierre mensual.', 'abierto', 120, 1440, DATE_SUB(NOW(), INTERVAL 3 HOUR)),
('TK-2026-0005', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'software', 'baja', 'Actualizar Adobe Acrobat', 'Solicito actualización de Adobe Acrobat a la última versión para poder editar formularios PDF.', 'abierto', 240, 2880, DATE_SUB(NOW(), INTERVAL 4 HOUR)),
('TK-2026-0006', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'hardware', 'media', 'Impresora atascada constantemente', 'La impresora HP del segundo piso se atasca cada vez que imprimo más de 5 páginas. Ya limpié los rodillos.', 'abierto', 120, 1440, DATE_SUB(NOW(), INTERVAL 5 HOUR)),
('TK-2026-0007', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'software', 'alta', 'Error en sistema de pesaje', 'El software de pesaje de contenedores muestra error "DB Connection Failed" al intentar registrar pesajes.', 'abierto', 60, 480, DATE_SUB(NOW(), INTERVAL 1 HOUR)),
('TK-2026-0008', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'red', 'media', 'VPN no conecta desde casa', 'Al intentar conectar la VPN corporativa desde mi casa, aparece el error "Connection Timeout" después de 30 segundos.', 'abierto', 120, 1440, DATE_SUB(NOW(), INTERVAL 6 HOUR)),
('TK-2026-0009', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'acceso', 'alta', 'Cuenta bloqueada por intentos fallidos', 'Mi cuenta de Windows se bloqueó después de 3 intentos fallidos. Necesito desbloqueo urgente para operar grúa.', 'abierto', 60, 480, DATE_SUB(NOW(), INTERVAL 45 MINUTE)),
('TK-2026-0010', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'otro', 'baja', 'Solicitar mouse ergonómico', 'Solicito un mouse ergonómico por recomendación médica debido a tendinitis en la muñeca derecha.', 'abierto', 240, 2880, DATE_SUB(NOW(), INTERVAL 8 HOUR)),
('TK-2026-0011', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'software', 'media', 'Outlook no sincroniza correos', 'Mi Outlook dejó de sincronizar correos nuevos desde ayer. Probé reiniciar y reconstruir el perfil sin éxito.', 'abierto', 120, 1440, DATE_SUB(NOW(), INTERVAL 12 HOUR)),
('TK-2026-0012', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'hardware', 'urgente', 'PC no enciende - Gerencia Finanzas', 'El computador del Gerente de Finanzas no enciende. Tiene presentación al directorio en 2 horas.', 'abierto', 30, 240, DATE_SUB(NOW(), INTERVAL 15 MINUTE)),
('TK-2026-0013', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'red', 'alta', 'WiFi intermitente en bodega', 'La conexión WiFi en la bodega principal se cae cada 10-15 minutos, afectando los lectores de código de barras.', 'abierto', 60, 480, DATE_SUB(NOW(), INTERVAL 2 HOUR)),
('TK-2026-0014', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'software', 'media', 'Teams no permite compartir pantalla', 'Al intentar compartir pantalla en Microsoft Teams, aparece un mensaje de permisos insuficientes.', 'abierto', 120, 1440, DATE_SUB(NOW(), INTERVAL 3 HOUR)),
('TK-2026-0015', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'acceso', 'media', 'Resetear contraseña de correo', 'Olvidé mi contraseña del correo corporativo y el enlace de recuperación no llega a mi email personal.', 'abierto', 120, 1440, DATE_SUB(NOW(), INTERVAL 4 HOUR)),
('TK-2026-0016', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'hardware', 'baja', 'Solicitar segundo monitor', 'Solicito un segundo monitor para mi estación de trabajo. Necesito más espacio de pantalla para hojas de cálculo.', 'abierto', 240, 2880, DATE_SUB(NOW(), INTERVAL 1 DAY)),
('TK-2026-0017', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'software', 'alta', 'Sistema de turnos muestra datos erróneos', 'El sistema de gestión de turnos muestra horarios incorrectos para la semana actual. Afecta a todo el equipo.', 'abierto', 60, 480, DATE_SUB(NOW(), INTERVAL 1 HOUR)),
('TK-2026-0018', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'red', 'media', 'No puedo acceder a carpeta compartida', 'La carpeta \\\\servidor\\compartida\\administracion me da error de acceso denegado desde hoy.', 'abierto', 120, 1440, DATE_SUB(NOW(), INTERVAL 5 HOUR)),
('TK-2026-0019', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'otro', 'media', 'Solicitar capacitación Power BI', 'Solicito capacitación en Power BI para generar reportes operacionales del área.', 'abierto', 120, 1440, DATE_SUB(NOW(), INTERVAL 2 DAY)),
('TK-2026-0020', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'software', 'urgente', 'Error crítico en cierre contable', 'El sistema contable arroja error al intentar cerrar el periodo de febrero. Fecha límite mañana.', 'abierto', 30, 240, DATE_SUB(NOW(), INTERVAL 20 MINUTE));

-- =============================================
-- ESTADO: ASIGNADO (20 tickets)
-- =============================================
INSERT INTO tickets (ticket_number, user_id, user_name, user_email, user_department, category, priority, title, description, status, assigned_to, assigned_by, assigned_at, first_response_at, sla_response_target, sla_resolution_target, sla_response_met, created_at) VALUES
('TK-2026-0021', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'hardware', 'media', 'Mouse inalámbrico no funciona', 'El mouse inalámbrico Logitech dejó de sincronizar con el receptor USB. Ya probé cambiar pilas.', 'asignado', 2, 1, DATE_SUB(NOW(), INTERVAL 3 HOUR), DATE_SUB(NOW(), INTERVAL 3 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 4 HOUR)),
('TK-2026-0022', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'software', 'alta', 'Error al generar boletas electrónicas', 'El sistema de facturación electrónica muestra error 500 al intentar emitir boletas. Urge para ventas del día.', 'asignado', 3, 1, DATE_SUB(NOW(), INTERVAL 1 HOUR), DATE_SUB(NOW(), INTERVAL 1 HOUR), 60, 480, 1, DATE_SUB(NOW(), INTERVAL 2 HOUR)),
('TK-2026-0023', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'red', 'urgente', 'Switch de red dañado en muelle 3', 'El switch de red del muelle 3 tiene luces ámbar parpadeando. Sin conectividad en toda esa zona.', 'asignado', 2, 1, DATE_SUB(NOW(), INTERVAL 20 MINUTE), DATE_SUB(NOW(), INTERVAL 20 MINUTE), 30, 240, 1, DATE_SUB(NOW(), INTERVAL 25 MINUTE)),
('TK-2026-0024', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'acceso', 'baja', 'Permisos de lectura en servidor de archivos', 'Necesito permisos de lectura en la carpeta \\\\servidor\\reportes\\2025 para auditoría anual.', 'asignado', 3, 1, DATE_SUB(NOW(), INTERVAL 6 HOUR), DATE_SUB(NOW(), INTERVAL 6 HOUR), 240, 2880, 1, DATE_SUB(NOW(), INTERVAL 8 HOUR)),
('TK-2026-0025', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'software', 'media', 'Antivirus bloquea aplicación interna', 'El antivirus Kaspersky bloquea la ejecución del sistema de control de acceso portuario cada vez que se abre.', 'asignado', 2, 1, DATE_SUB(NOW(), INTERVAL 5 HOUR), DATE_SUB(NOW(), INTERVAL 5 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 6 HOUR)),
('TK-2026-0026', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'hardware', 'alta', 'UPS hace ruido y parpadea', 'El UPS de la oficina de Administración emite pitidos intermitentes y la luz del indicador parpadea rojo.', 'asignado', 3, 1, DATE_SUB(NOW(), INTERVAL 2 HOUR), DATE_SUB(NOW(), INTERVAL 2 HOUR), 60, 480, 1, DATE_SUB(NOW(), INTERVAL 3 HOUR)),
('TK-2026-0027', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'red', 'media', 'Cámara IP sin señal en puerta 2', 'La cámara de seguridad IP de la puerta 2 no transmite imagen desde ayer en la noche.', 'asignado', 2, 1, DATE_SUB(NOW(), INTERVAL 10 HOUR), DATE_SUB(NOW(), INTERVAL 10 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 12 HOUR)),
('TK-2026-0028', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'software', 'media', 'Macro de Excel no funciona correctamente', 'La macro de consolidación de datos financieros lanza error en la línea 45. Antes funcionaba bien.', 'asignado', 3, 1, DATE_SUB(NOW(), INTERVAL 4 HOUR), DATE_SUB(NOW(), INTERVAL 4 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 5 HOUR)),
('TK-2026-0029', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'acceso', 'alta', 'Acceso al sistema de monitoreo portuario', 'Necesito credenciales para el nuevo sistema de monitoreo de operaciones marítimas SCOM v3.', 'asignado', 2, 1, DATE_SUB(NOW(), INTERVAL 1 HOUR), DATE_SUB(NOW(), INTERVAL 1 HOUR), 60, 480, 1, DATE_SUB(NOW(), INTERVAL 2 HOUR)),
('TK-2026-0030', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'otro', 'baja', 'Reorganizar cableado del escritorio', 'Solicito que reorganicen el cableado de mi puesto de trabajo, hay muchos cables sueltos y es peligroso.', 'asignado', 3, 1, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), 240, 2880, 1, DATE_SUB(NOW(), INTERVAL 1 DAY)),
('TK-2026-0031', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'hardware', 'urgente', 'Escáner de documentos no funciona', 'El escáner de la oficina de despacho no enciende. Se necesita para digitalizar guías de despacho hoy.', 'asignado', 2, 1, DATE_SUB(NOW(), INTERVAL 15 MINUTE), DATE_SUB(NOW(), INTERVAL 15 MINUTE), 30, 240, 1, DATE_SUB(NOW(), INTERVAL 20 MINUTE)),
('TK-2026-0032', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'software', 'alta', 'SAP no genera reportes de IVA', 'El módulo de impuestos de SAP no genera el reporte mensual de IVA. Error: "Tax period not found".', 'asignado', 3, 1, DATE_SUB(NOW(), INTERVAL 30 MINUTE), DATE_SUB(NOW(), INTERVAL 30 MINUTE), 60, 480, 1, DATE_SUB(NOW(), INTERVAL 1 HOUR)),
('TK-2026-0033', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'red', 'media', 'Internet lento en oficina planta baja', 'La velocidad de internet en toda la planta baja es muy lenta. Speed test da 5 Mbps cuando debería ser 100.', 'asignado', 2, 1, DATE_SUB(NOW(), INTERVAL 7 HOUR), DATE_SUB(NOW(), INTERVAL 7 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 8 HOUR)),
('TK-2026-0034', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'software', 'media', 'Error al abrir archivos Word compartidos', 'Los documentos Word en la carpeta compartida se abren en modo solo lectura aunque tengo permisos de edición.', 'asignado', 3, 1, DATE_SUB(NOW(), INTERVAL 6 HOUR), DATE_SUB(NOW(), INTERVAL 6 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 7 HOUR)),
('TK-2026-0035', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'hardware', 'baja', 'Solicitar headset para reuniones', 'Necesito un headset con micrófono para participar en reuniones Teams desde la oficina compartida.', 'asignado', 2, 1, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 240, 2880, 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),
('TK-2026-0036', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'acceso', 'media', 'Acceso a portal bancario corporativo', 'Necesito acceso al portal web del Banco Estado para gestionar transferencias del área financiera.', 'asignado', 3, 1, DATE_SUB(NOW(), INTERVAL 3 HOUR), DATE_SUB(NOW(), INTERVAL 3 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 4 HOUR)),
('TK-2026-0037', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'software', 'alta', 'Aplicación de logística se congela', 'El software LogiPort se congela al cargar el módulo de contenedores. Hay que forzar cierre con Task Manager.', 'asignado', 2, 1, DATE_SUB(NOW(), INTERVAL 45 MINUTE), DATE_SUB(NOW(), INTERVAL 45 MINUTE), 60, 480, 1, DATE_SUB(NOW(), INTERVAL 1 HOUR)),
('TK-2026-0038', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'otro', 'media', 'Instalar extensión eléctrica certificada', 'Necesito una extensión eléctrica certificada para conectar equipos adicionales en mi puesto de trabajo.', 'asignado', 3, 1, DATE_SUB(NOW(), INTERVAL 8 HOUR), DATE_SUB(NOW(), INTERVAL 8 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 9 HOUR)),
('TK-2026-0039', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'red', 'urgente', 'Radio de comunicación sin frecuencia', 'Las radios de comunicación del muelle perdieron la frecuencia principal. Imposible coordinar operaciones.', 'asignado', 2, 1, DATE_SUB(NOW(), INTERVAL 10 MINUTE), DATE_SUB(NOW(), INTERVAL 10 MINUTE), 30, 240, 1, DATE_SUB(NOW(), INTERVAL 12 MINUTE)),
('TK-2026-0040', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'hardware', 'media', 'Disco duro externo no es reconocido', 'El disco duro externo Seagate 2TB no aparece al conectar por USB. Contiene respaldo de datos contables.', 'asignado', 3, 1, DATE_SUB(NOW(), INTERVAL 4 HOUR), DATE_SUB(NOW(), INTERVAL 4 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 5 HOUR));

-- =============================================
-- ESTADO: EN_PROCESO (20 tickets)
-- =============================================
INSERT INTO tickets (ticket_number, user_id, user_name, user_email, user_department, category, priority, title, description, status, assigned_to, assigned_by, assigned_at, first_response_at, work_started_at, sla_response_target, sla_resolution_target, sla_response_met, created_at) VALUES
('TK-2026-0041', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'red', 'urgente', 'Firewall bloqueando tráfico legítimo', 'El firewall está bloqueando el acceso a sitios del SII y Tesorería. Afecta a toda la empresa.', 'en_proceso', 2, 1, DATE_SUB(NOW(), INTERVAL 2 HOUR), DATE_SUB(NOW(), INTERVAL 2 HOUR), DATE_SUB(NOW(), INTERVAL 1 HOUR), 30, 240, 1, DATE_SUB(NOW(), INTERVAL 3 HOUR)),
('TK-2026-0042', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'software', 'alta', 'Migración de buzón de correo', 'Migrar buzón de correo de Exchange on-premise a Office 365. Ya se inició la copia de datos.', 'en_proceso', 3, 1, DATE_SUB(NOW(), INTERVAL 6 HOUR), DATE_SUB(NOW(), INTERVAL 6 HOUR), DATE_SUB(NOW(), INTERVAL 5 HOUR), 60, 480, 1, DATE_SUB(NOW(), INTERVAL 8 HOUR)),
('TK-2026-0043', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'hardware', 'media', 'Reemplazo de disco duro SSD', 'El disco duro del equipo muestra errores SMART. Se está clonando a un SSD nuevo.', 'en_proceso', 2, 1, DATE_SUB(NOW(), INTERVAL 4 HOUR), DATE_SUB(NOW(), INTERVAL 4 HOUR), DATE_SUB(NOW(), INTERVAL 3 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 6 HOUR)),
('TK-2026-0044', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'acceso', 'alta', 'Configurar MFA para portal de bancos', 'Configuración de autenticación multifactor para acceso al portal bancario corporativo. En proceso de registro.', 'en_proceso', 3, 1, DATE_SUB(NOW(), INTERVAL 2 HOUR), DATE_SUB(NOW(), INTERVAL 2 HOUR), DATE_SUB(NOW(), INTERVAL 1 HOUR), 60, 480, 1, DATE_SUB(NOW(), INTERVAL 3 HOUR)),
('TK-2026-0045', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'software', 'urgente', 'Servidor de base de datos lento', 'El servidor MySQL de producción tiene latencia de 5 segundos por query. Analizando índices y queries.', 'en_proceso', 2, 1, DATE_SUB(NOW(), INTERVAL 1 HOUR), DATE_SUB(NOW(), INTERVAL 1 HOUR), DATE_SUB(NOW(), INTERVAL 45 MINUTE), 30, 240, 1, DATE_SUB(NOW(), INTERVAL 2 HOUR)),
('TK-2026-0046', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'red', 'media', 'Configurar nueva impresora de red', 'Instalación y configuración de nueva impresora Xerox en el departamento de Administración. Driver en instalación.', 'en_proceso', 3, 1, DATE_SUB(NOW(), INTERVAL 3 HOUR), DATE_SUB(NOW(), INTERVAL 3 HOUR), DATE_SUB(NOW(), INTERVAL 2 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 4 HOUR)),
('TK-2026-0047', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'hardware', 'alta', 'Reparar proyector de sala de reuniones', 'El proyector Epson de la sala principal no muestra imagen. Se está revisando la lámpara y las conexiones.', 'en_proceso', 2, 1, DATE_SUB(NOW(), INTERVAL 2 HOUR), DATE_SUB(NOW(), INTERVAL 2 HOUR), DATE_SUB(NOW(), INTERVAL 1 HOUR), 60, 480, 1, DATE_SUB(NOW(), INTERVAL 3 HOUR)),
('TK-2026-0048', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'software', 'media', 'Instalar certificado digital SII', 'Instalación del certificado digital del SII en el equipo de contabilidad. Descargando certificado raíz.', 'en_proceso', 3, 1, DATE_SUB(NOW(), INTERVAL 5 HOUR), DATE_SUB(NOW(), INTERVAL 5 HOUR), DATE_SUB(NOW(), INTERVAL 4 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 6 HOUR)),
('TK-2026-0049', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'otro', 'media', 'Actualización firmware equipos de red', 'Actualización programada del firmware de switches y access points del edificio. 60% completado.', 'en_proceso', 2, 1, DATE_SUB(NOW(), INTERVAL 8 HOUR), DATE_SUB(NOW(), INTERVAL 8 HOUR), DATE_SUB(NOW(), INTERVAL 6 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 10 HOUR)),
('TK-2026-0050', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'acceso', 'alta', 'Reseteo masivo contraseñas dpto.', 'Reseteo de contraseñas para 8 usuarios del departamento tras incidente de phishing. 5 de 8 completados.', 'en_proceso', 3, 1, DATE_SUB(NOW(), INTERVAL 1 HOUR), DATE_SUB(NOW(), INTERVAL 1 HOUR), DATE_SUB(NOW(), INTERVAL 50 MINUTE), 60, 480, 1, DATE_SUB(NOW(), INTERVAL 2 HOUR)),
('TK-2026-0051', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'software', 'urgente', 'Restaurar backup de base de datos', 'Se corrompió la base de datos del sistema de inventario. Restaurando desde backup de anoche.', 'en_proceso', 2, 1, DATE_SUB(NOW(), INTERVAL 45 MINUTE), DATE_SUB(NOW(), INTERVAL 45 MINUTE), DATE_SUB(NOW(), INTERVAL 30 MINUTE), 30, 240, 1, DATE_SUB(NOW(), INTERVAL 1 HOUR)),
('TK-2026-0052', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'hardware', 'media', 'Instalar memoria RAM adicional', 'El equipo de contabilidad necesita más RAM. Se están instalando 16GB adicionales. Equipo desarmado.', 'en_proceso', 3, 1, DATE_SUB(NOW(), INTERVAL 3 HOUR), DATE_SUB(NOW(), INTERVAL 3 HOUR), DATE_SUB(NOW(), INTERVAL 2 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 4 HOUR)),
('TK-2026-0053', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'red', 'alta', 'Reconectar fibra óptica cortada', 'Se cortó un tramo de fibra óptica en el ducto entre edificios. Técnico fusionando fibra actualmente.', 'en_proceso', 2, 1, DATE_SUB(NOW(), INTERVAL 3 HOUR), DATE_SUB(NOW(), INTERVAL 3 HOUR), DATE_SUB(NOW(), INTERVAL 2 HOUR), 60, 480, 1, DATE_SUB(NOW(), INTERVAL 4 HOUR)),
('TK-2026-0054', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'software', 'media', 'Configurar nuevo equipo Windows 11', 'Configuración de nuevo laptop Dell para directora de Administración. Instalando Office y software corporativo.', 'en_proceso', 3, 1, DATE_SUB(NOW(), INTERVAL 6 HOUR), DATE_SUB(NOW(), INTERVAL 6 HOUR), DATE_SUB(NOW(), INTERVAL 5 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 7 HOUR)),
('TK-2026-0055', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'acceso', 'media', 'Habilitar acceso remoto escritorio', 'Configurando RDP para que Carlos pueda acceder remotamente al servidor de turnos desde su casa.', 'en_proceso', 2, 1, DATE_SUB(NOW(), INTERVAL 4 HOUR), DATE_SUB(NOW(), INTERVAL 4 HOUR), DATE_SUB(NOW(), INTERVAL 3 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 5 HOUR)),
('TK-2026-0056', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'software', 'alta', 'Actualizar sistema contable Softland', 'Actualización del sistema contable Softland a versión 2026.1. Respaldo completado, instalando parche.', 'en_proceso', 3, 1, DATE_SUB(NOW(), INTERVAL 2 HOUR), DATE_SUB(NOW(), INTERVAL 2 HOUR), DATE_SUB(NOW(), INTERVAL 1 HOUR), 60, 480, 1, DATE_SUB(NOW(), INTERVAL 3 HOUR)),
('TK-2026-0057', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'hardware', 'urgente', 'Servidor principal sobrecalentado', 'Alarma de temperatura en el servidor principal del datacenter. Revisando ventiladores y AC de sala.', 'en_proceso', 2, 1, DATE_SUB(NOW(), INTERVAL 30 MINUTE), DATE_SUB(NOW(), INTERVAL 30 MINUTE), DATE_SUB(NOW(), INTERVAL 20 MINUTE), 30, 240, 1, DATE_SUB(NOW(), INTERVAL 40 MINUTE)),
('TK-2026-0058', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'red', 'media', 'Extender red WiFi a nueva oficina', 'Instalación de access point TP-Link en la nueva oficina del tercer piso. Tendido de cable en proceso.', 'en_proceso', 3, 1, DATE_SUB(NOW(), INTERVAL 5 HOUR), DATE_SUB(NOW(), INTERVAL 5 HOUR), DATE_SUB(NOW(), INTERVAL 4 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 6 HOUR)),
('TK-2026-0059', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'software', 'media', 'Migrar datos a nuevo servidor', 'Migrando 500GB de datos operacionales al nuevo servidor NAS. Transferencia al 70%.', 'en_proceso', 2, 1, DATE_SUB(NOW(), INTERVAL 12 HOUR), DATE_SUB(NOW(), INTERVAL 12 HOUR), DATE_SUB(NOW(), INTERVAL 10 HOUR), 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 14 HOUR)),
('TK-2026-0060', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'otro', 'baja', 'Limpieza profunda de equipos Finanzas', 'Limpieza interna de polvo en los 6 equipos del área de Finanzas. 4 de 6 completados.', 'en_proceso', 3, 1, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 20 HOUR), 240, 2880, 1, DATE_SUB(NOW(), INTERVAL 2 DAY));

-- =============================================
-- ESTADO: PENDIENTE (20 tickets)
-- =============================================
INSERT INTO tickets (ticket_number, user_id, user_name, user_email, user_department, category, priority, title, description, status, assigned_to, assigned_by, assigned_at, first_response_at, work_started_at, resolution, sla_response_target, sla_resolution_target, sla_response_met, created_at) VALUES
('TK-2026-0061', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'hardware', 'alta', 'Reemplazo de pantalla notebook', 'La pantalla del notebook tiene líneas verticales. Pendiente llegada del repuesto desde Santiago (3 días hábiles).', 'pendiente', 2, 1, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 'Pendiente repuesto - pantalla LCD 15.6" HP. Proveedor confirma despacho el viernes.', 60, 480, 1, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('TK-2026-0062', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'software', 'media', 'Licencia Office 365 expirada', 'La licencia de Office 365 expiró y no se puede renovar. Pendiente aprobación de presupuesto por gerencia.', 'pendiente', 3, 1, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 'En espera de aprobación de orden de compra por Gerencia General.', 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 4 DAY)),
('TK-2026-0063', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'red', 'urgente', 'Enlace de fibra con proveedor caído', 'El enlace de fibra principal del ISP está caído. Proveedor informa corte por obras en carretera.', 'pendiente', 2, 1, DATE_SUB(NOW(), INTERVAL 6 HOUR), DATE_SUB(NOW(), INTERVAL 6 HOUR), DATE_SUB(NOW(), INTERVAL 5 HOUR), 'Proveedor ISP informa reparación estimada en 12 horas. Operando con enlace de respaldo.', 30, 240, 1, DATE_SUB(NOW(), INTERVAL 8 HOUR)),
('TK-2026-0064', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'acceso', 'media', 'Solicitud acceso sistema RRHH', 'Se requiere autorización de la gerencia de RRHH para otorgar acceso al módulo de remuneraciones.', 'pendiente', 3, 1, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 'Esperando firma de autorización del Gerente de RRHH. Se envió correo recordatorio.', 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('TK-2026-0065', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'hardware', 'media', 'Batería de notebook hinchada', 'La batería del notebook está hinchada y deforma el trackpad. Esperando batería de reemplazo OEM.', 'pendiente', 2, 1, DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), 'Batería encargada a proveedor Dell. ETA: próxima semana. Equipo en uso conectado a corriente.', 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 5 DAY)),
('TK-2026-0066', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'software', 'alta', 'Error persistente en sistema de RRHH', 'Bug en el cálculo de vacaciones del sistema de RRHH. Se escaló al proveedor del software.', 'pendiente', 3, 1, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 'Caso abierto con proveedor Softland - Ticket #SR-45672. Esperando parche correctivo.', 60, 480, 1, DATE_SUB(NOW(), INTERVAL 4 DAY)),
('TK-2026-0067', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'otro', 'baja', 'Compra de reguladores de voltaje', 'Se necesitan 5 reguladores de voltaje para los equipos de operaciones. Pendiente cotización.', 'pendiente', 2, 1, DATE_SUB(NOW(), INTERVAL 1 WEEK), DATE_SUB(NOW(), INTERVAL 1 WEEK), DATE_SUB(NOW(), INTERVAL 6 DAY), 'Se enviaron 3 cotizaciones a Adquisiciones. En proceso de comparación de precios.', 240, 2880, 1, DATE_SUB(NOW(), INTERVAL 8 DAY)),
('TK-2026-0068', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'software', 'media', 'Integración ERP con banco', 'La integración entre SAP y el portal bancario requiere certificado SSL del banco. Solicitado hace 5 días.', 'pendiente', 3, 1, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), 'Banco confirma emisión de certificado en 3-5 días hábiles. Caso ref: BC-2026-1199.', 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 6 DAY)),
('TK-2026-0069', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'hardware', 'urgente', 'Servidor de cámaras con disco lleno', 'El NVR de cámaras tiene el disco al 98%. Se necesita disco de 8TB. Pendiente compra de emergencia.', 'pendiente', 2, 1, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), 'OC emitida. Proveedor entrega mañana. Mientras tanto se eliminaron grabaciones antiguas no críticas.', 30, 240, 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),
('TK-2026-0070', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'acceso', 'media', 'Migración a Azure AD', 'La migración de cuentas a Azure AD está pausada esperando la activación de la suscripción E3.', 'pendiente', 3, 1, DATE_SUB(NOW(), INTERVAL 1 WEEK), DATE_SUB(NOW(), INTERVAL 1 WEEK), DATE_SUB(NOW(), INTERVAL 6 DAY), 'Microsoft confirma activación de licencias E3 para el próximo lunes.', 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 8 DAY)),
('TK-2026-0071', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'red', 'alta', 'Ampliar ancho de banda enlace', 'Se requiere ampliar el enlace de internet de 100Mbps a 500Mbps. Pendiente contrato con proveedor.', 'pendiente', 2, 1, DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 10 DAY), 'Propuesta comercial aprobada por Gerencia. ISP agenda instalación técnica para el 5 de marzo.', 60, 480, 1, DATE_SUB(NOW(), INTERVAL 2 WEEK)),
('TK-2026-0072', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'software', 'alta', 'Bug en cálculo de depreciación', 'El módulo de activos fijos calcula mal la depreciación acelerada. Escalado al desarrollador.', 'pendiente', 3, 1, DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 'Proveedor confirmó bug. Hotfix programado para el próximo release v2026.1.3.', 60, 480, 1, DATE_SUB(NOW(), INTERVAL 5 DAY)),
('TK-2026-0073', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'hardware', 'media', 'Reemplazo masivo de teclados', 'Se aprobó el reemplazo de 20 teclados dañados por desgaste. Orden de compra emitida.', 'pendiente', 2, 1, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 'Proveedor PCFactory confirma despacho de 20 teclados Logitech K120 para el jueves.', 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 4 DAY)),
('TK-2026-0074', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'otro', 'baja', 'Reestructurar cableado sala servidores', 'Se necesita reestructurar el cableado del rack principal. Pendiente ventana de mantenimiento.', 'pendiente', 3, 1, DATE_SUB(NOW(), INTERVAL 1 WEEK), DATE_SUB(NOW(), INTERVAL 1 WEEK), DATE_SUB(NOW(), INTERVAL 5 DAY), 'Ventana de mantenimiento programada para sábado 8 de marzo, 22:00-06:00.', 240, 2880, 1, DATE_SUB(NOW(), INTERVAL 10 DAY)),
('TK-2026-0075', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'software', 'media', 'Actualizar antivirus en 50 equipos', 'La actualización del antivirus requiere reinicio. Coordinando con cada departamento para horarios.', 'pendiente', 2, 1, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), '30 de 50 equipos actualizados. Los 20 restantes serán durante la noche del miércoles.', 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 4 DAY)),
('TK-2026-0076', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'acceso', 'alta', 'Token de seguridad bancario dañado', 'El token físico del banco se dañó. Banco solicita nota formal de la empresa para reemplazo.', 'pendiente', 3, 1, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 'Carta firmada por Gerente General enviada al banco. Esperando nuevo token en 48 horas.', 60, 480, 1, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('TK-2026-0077', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'red', 'media', 'Instalar punto de red en nueva oficina', 'Se necesita cableado estructurado para 4 nuevos puestos de trabajo. Pendiente compra de materiales.', 'pendiente', 2, 1, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), 'Materiales (cable UTP Cat6, jacks, canaletas) llegarán el viernes.', 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 6 DAY)),
('TK-2026-0078', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'hardware', 'media', 'Impresora necesita mantenimiento preventivo', 'La impresora Xerox requiere cambio de drum y fusor. Repuestos en camino desde Santiago.', 'pendiente', 3, 1, DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 'Drum y fusor Xerox despachados via Chilexpress. Tracking: 99912345678.', 120, 1440, 1, DATE_SUB(NOW(), INTERVAL 5 DAY)),
('TK-2026-0079', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'software', 'urgente', 'Parche de seguridad crítico Windows', 'Vulnerabilidad CVE-2026-0012 requiere parche urgente en servidores. Esperando ventana de mantenimiento.', 'pendiente', 2, 1, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), 'Parche descargado y testeado en entorno QA. Despliegue programado esta noche a las 23:00.', 30, 240, 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),
('TK-2026-0080', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'otro', 'baja', 'Cotización de laptops nuevos 2026', 'Se requieren 10 laptops nuevos para el plan de renovación 2026. Pendiente aprobación de presupuesto.', 'pendiente', 3, 1, DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 12 DAY), '3 cotizaciones entregadas a Gerencia. Presupuesto en evaluación para aprobación en comité del viernes.', 240, 2880, 1, DATE_SUB(NOW(), INTERVAL 15 DAY));

-- =============================================
-- ESTADO: RESUELTO (20 tickets)
-- =============================================
INSERT INTO tickets (ticket_number, user_id, user_name, user_email, user_department, category, priority, title, description, status, assigned_to, assigned_by, assigned_at, first_response_at, work_started_at, resolved_at, resolution, resolution_type, sla_response_target, sla_resolution_target, sla_response_met, sla_resolution_met, created_at) VALUES
('TK-2026-0081', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'software', 'media', 'Outlook no envía correos', 'Outlook muestra error "Cannot connect to server" al intentar enviar correos electrónicos.', 'resuelto', 2, 1, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 23 HOUR), DATE_SUB(NOW(), INTERVAL 20 HOUR), 'Se reconfiguró el perfil de Outlook y se actualizó la configuración SMTP. Correos funcionando correctamente.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),
('TK-2026-0082', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'hardware', 'alta', 'Monitor parpadea intermitentemente', 'El monitor Dell de mi estación parpadea cada 2-3 segundos. Imposible trabajar así.', 'resuelto', 3, 1, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), 'Se reemplazó el cable DisplayPort dañado por uno nuevo. Monitor funcionando sin parpadeo.', 'solucionado', 60, 480, 1, 1, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('TK-2026-0083', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'red', 'urgente', 'Corte total de red en bodega', 'Toda la bodega principal quedó sin red. Afecta lectores de código y sistema de inventario.', 'resuelto', 2, 1, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 'Puerto del switch principal estaba configurado como trunk en vez de access. Reconfigurado y verificado.', 'solucionado', 30, 240, 1, 1, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('TK-2026-0084', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'acceso', 'media', 'No puedo acceder al portal tributario', 'Al ingresar al portal del SII, aparece error de certificado SSL. No permite continuar.', 'resuelto', 3, 1, DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 'Se instaló el certificado raíz del SII en el navegador. Acceso restaurado exitosamente.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 5 DAY)),
('TK-2026-0085', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'software', 'baja', 'Instalar 7-Zip en equipo', 'Necesito el programa 7-Zip para descomprimir archivos .7z que me envían los proveedores.', 'resuelto', 2, 1, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), 'Se instaló 7-Zip versión 24.09 (64-bit). Archivos .7z se abren correctamente.', 'solucionado', 240, 2880, 1, 1, DATE_SUB(NOW(), INTERVAL 6 DAY)),
('TK-2026-0086', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'red', 'media', 'WiFi no aparece en laptop', 'Mi laptop no detecta ninguna red WiFi. El icono de WiFi tiene una X roja.', 'resuelto', 3, 1, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 18 HOUR), 'El adaptador WiFi estaba deshabilitado. Se habilitó desde Administrador de Dispositivos y se actualizó el driver.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),
('TK-2026-0087', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'hardware', 'alta', 'Fuente de poder quemada', 'El PC de la estación de monitoreo no enciende. Se escuchó un pop y salió olor a quemado.', 'resuelto', 2, 1, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 'Se reemplazó fuente de poder quemada por Corsair 650W nueva. Equipo funcionando sin problemas.', 'solucionado', 60, 480, 1, 1, DATE_SUB(NOW(), INTERVAL 4 DAY)),
('TK-2026-0088', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'acceso', 'alta', 'Desbloquear cuenta Active Directory', 'Mi cuenta de red se bloqueó y no puedo iniciar sesión en Windows.', 'resuelto', 3, 1, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 'Cuenta desbloqueada en Active Directory y contraseña temporal asignada. Usuario cambió contraseña exitosamente.', 'solucionado', 60, 480, 1, 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),
('TK-2026-0089', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'software', 'media', 'Error Java en aplicación portuaria', 'La aplicación PortControl muestra "Java Runtime Error" al iniciar. No se puede registrar movimiento de carga.', 'resuelto', 2, 1, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), 'Se desinstaló Java 8 corrupto e instaló Java 17 LTS. Aplicación PortControl funciona correctamente.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 6 DAY)),
('TK-2026-0090', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'otro', 'baja', 'Etiquetar cables de red en oficina', 'Los cables de red del rack de Administración no están etiquetados. Dificulta el troubleshooting.', 'resuelto', 3, 1, DATE_SUB(NOW(), INTERVAL 1 WEEK), DATE_SUB(NOW(), INTERVAL 1 WEEK), DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 'Se etiquetaron los 24 cables de red con etiquetas impresas (puerto, ubicación, usuario).', 'solucionado', 240, 2880, 1, 1, DATE_SUB(NOW(), INTERVAL 8 DAY)),
('TK-2026-0091', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'hardware', 'urgente', 'Lector de código de barras dañado', 'El lector de código de barras de la estación de recepción no lee correctamente.', 'resuelto', 2, 1, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 22 HOUR), 'Se limpió la ventana del láser y se reconfiguró el baudrate. Lector funcionando al 100%.', 'solucionado', 30, 240, 1, 1, DATE_SUB(NOW(), INTERVAL 1 DAY)),
('TK-2026-0092', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'software', 'media', 'Excel muestra texto en vez de números', 'Las celdas de Excel muestran fórmulas como texto en vez de calcular el resultado.', 'resuelto', 3, 1, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 'Las celdas estaban formateadas como Texto. Se cambió formato a Número y se recalculó la hoja.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 4 DAY)),
('TK-2026-0093', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'red', 'alta', 'Punto de acceso WiFi no responde', 'El AP Ubiquiti del muelle 1 dejó de funcionar. Sin WiFi en toda esa zona.', 'resuelto', 2, 1, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), 'El AP tenía firmware corrupto. Se restauró de fábrica y se reconfiguró con perfil estándar.', 'solucionado', 60, 480, 1, 1, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('TK-2026-0094', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'acceso', 'media', 'Crear cuenta para nuevo colaborador', 'Se necesita cuenta de correo, AD y acceso a sistemas para nuevo colaborador Juan Tapia.', 'resuelto', 3, 1, DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 'Cuenta creada: juan.tapia@puertocoquimbo.cl - AD, Office 365, VPN y acceso a carpeta de Administración configurados.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 5 DAY)),
('TK-2026-0095', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'software', 'alta', 'Windows Update falla con error 0x800', 'Windows Update muestra error 0x80070002 y no puede instalar actualizaciones de seguridad.', 'resuelto', 2, 1, DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), 'Se ejecutó DISM /RestoreHealth y SFC /scannow. Componentes reparados, actualizaciones instaladas.', 'solucionado', 60, 480, 1, 1, DATE_SUB(NOW(), INTERVAL 7 DAY)),
('TK-2026-0096', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'hardware', 'media', 'Parlantes del PC no funcionan', 'Los parlantes integrados del monitor no reproducen sonido. Audio funciona con audífonos.', 'resuelto', 3, 1, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 'El dispositivo de audio por defecto estaba configurado en HDMI. Se cambió a los parlantes del monitor.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('TK-2026-0097', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'otro', 'media', 'Limpieza de virus en USB', 'Una USB del área contiene un virus detectado por Kaspersky. No se puede acceder a los archivos.', 'resuelto', 2, 1, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 20 HOUR), 'Se eliminó malware tipo ransomware. Archivos recuperados del último backup. USB formateada.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),
('TK-2026-0098', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'software', 'urgente', 'Sistema de asistencia caído', 'El sistema de control de asistencia (reloj biométrico) no registra marcaciones desde las 7:00 AM.', 'resuelto', 3, 1, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), 'El servicio del software ZKAccess estaba detenido. Se reinició y se sincronizaron las marcaciones pendientes.', 'solucionado', 30, 240, 1, 1, DATE_SUB(NOW(), INTERVAL 5 DAY)),
('TK-2026-0099', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'hardware', 'media', 'Cambiar tóner de impresora', 'La impresora HP LaserJet indica "tóner bajo". Las impresiones salen muy claras.', 'resuelto', 2, 1, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 'Se reemplazó tóner HP 26A por uno nuevo. Calidad de impresión restaurada.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('TK-2026-0100', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'red', 'alta', 'Carpeta compartida inaccesible', 'No puedo acceder a \\\\servidor\\finanzas desde mi equipo. Error: "No se puede acceder a la red".', 'resuelto', 3, 1, DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 'El protocolo SMBv1 estaba deshabilitado. Se habilitó SMBv3 y se mapeó la unidad correctamente.', 'solucionado', 60, 480, 1, 1, DATE_SUB(NOW(), INTERVAL 5 DAY));

-- =============================================
-- ESTADO: CERRADO (20 tickets)
-- =============================================
INSERT INTO tickets (ticket_number, user_id, user_name, user_email, user_department, category, priority, title, description, status, assigned_to, assigned_by, assigned_at, first_response_at, work_started_at, resolved_at, closed_at, resolution, resolution_type, sla_response_target, sla_resolution_target, sla_response_met, sla_resolution_met, created_at) VALUES
('TK-2026-0101', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'software', 'media', 'Instalar driver de impresora', 'Necesito el driver de la impresora HP LaserJet Pro del piso 1 para poder imprimir desde mi equipo.', 'cerrado', 2, 1, DATE_SUB(NOW(), INTERVAL 1 WEEK), DATE_SUB(NOW(), INTERVAL 1 WEEK), DATE_SUB(NOW(), INTERVAL 1 WEEK), DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), 'Driver HP Universal instalado. Impresora configurada y test de impresión exitoso.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 8 DAY)),
('TK-2026-0102', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'hardware', 'alta', 'Cambio de teclado roto', 'Varias teclas de mi teclado no responden. Necesito reemplazo urgente.', 'cerrado', 3, 1, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 9 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY), 'Teclado reemplazado por Logitech K120 nuevo. Funcionando correctamente.', 'solucionado', 60, 480, 1, 1, DATE_SUB(NOW(), INTERVAL 11 DAY)),
('TK-2026-0103', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'red', 'urgente', 'Pérdida total de conectividad muelle 1', 'El switch principal del muelle 1 dejó de funcionar. Sin red en toda la zona portuaria.', 'cerrado', 2, 1, DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 13 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY), 'Switch reemplazado por Cisco 2960 de respaldo. Red del muelle restaurada al 100%.', 'solucionado', 30, 240, 1, 1, DATE_SUB(NOW(), INTERVAL 15 DAY)),
('TK-2026-0104', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'acceso', 'media', 'Renovación de contraseña Windows', 'Windows me solicita cambiar contraseña pero no acepta la nueva que ingreso.', 'cerrado', 3, 1, DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 11 DAY), 'La política de AD requería caracteres especiales. Se ayudó al usuario a crear contraseña compatible.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 13 DAY)),
('TK-2026-0105', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'software', 'baja', 'Solicitar licencia AutoCAD', 'Necesito licencia de AutoCAD LT para revisar planos de infraestructura portuaria.', 'cerrado', 2, 1, DATE_SUB(NOW(), INTERVAL 3 WEEK), DATE_SUB(NOW(), INTERVAL 3 WEEK), DATE_SUB(NOW(), INTERVAL 20 DAY), DATE_SUB(NOW(), INTERVAL 15 DAY), DATE_SUB(NOW(), INTERVAL 14 DAY), 'Se asignó licencia flotante de AutoCAD LT 2026. Activada y verificada en el equipo.', 'solucionado', 240, 2880, 1, 1, DATE_SUB(NOW(), INTERVAL 22 DAY)),
('TK-2026-0106', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'hardware', 'media', 'PC se reinicia solo constantemente', 'Mi computador se reinicia automáticamente cada 30-40 minutos sin previo aviso.', 'cerrado', 3, 1, DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 9 DAY), 'Problema de sobrecalentamiento por pasta térmica seca. Se reemplazó pasta y se limpió ventilador.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 15 DAY)),
('TK-2026-0107', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'acceso', 'alta', 'Acceso VPN para teletrabajo', 'Necesito configurar acceso VPN para trabajar desde casa durante licencia médica.', 'cerrado', 2, 1, DATE_SUB(NOW(), INTERVAL 3 WEEK), DATE_SUB(NOW(), INTERVAL 3 WEEK), DATE_SUB(NOW(), INTERVAL 3 WEEK), DATE_SUB(NOW(), INTERVAL 20 DAY), DATE_SUB(NOW(), INTERVAL 19 DAY), 'Cliente VPN FortiClient instalado y configurado. Prueba de conexión remota exitosa.', 'solucionado', 60, 480, 1, 1, DATE_SUB(NOW(), INTERVAL 22 DAY)),
('TK-2026-0108', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'software', 'media', 'Error en macro de conciliación bancaria', 'La macro de Excel para conciliación bancaria da error "Type mismatch" en la línea 127.', 'cerrado', 3, 1, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY), 'Se corrigió la macro: variable declarada como String debía ser Double. Macro funcionando.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 12 DAY)),
('TK-2026-0109', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'red', 'alta', 'Teléfono IP sin tono de marcado', 'El teléfono IP Yealink de mi escritorio no tiene tono. Pantalla encendida pero sin servicio.', 'cerrado', 2, 1, DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY), 'El teléfono perdió registro SIP. Se reconfiguró contra el servidor Asterisk. Llamadas OK.', 'solucionado', 60, 480, 1, 1, DATE_SUB(NOW(), INTERVAL 9 DAY)),
('TK-2026-0110', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'otro', 'baja', 'Instalar soporte para monitor', 'Solicito instalación de brazo soporte para monitor y así mejorar ergonomía del puesto.', 'cerrado', 3, 1, DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 9 DAY), 'Brazo articulado instalado correctamente. Monitor ajustado a altura ergonómica.', 'solucionado', 240, 2880, 1, 1, DATE_SUB(NOW(), INTERVAL 16 DAY)),
('TK-2026-0111', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'software', 'urgente', 'Virus detectado en servidor de archivos', 'Kaspersky detectó un ransomware en el servidor de archivos compartidos. Archivos encriptados.', 'cerrado', 2, 1, DATE_SUB(NOW(), INTERVAL 1 WEEK), DATE_SUB(NOW(), INTERVAL 1 WEEK), DATE_SUB(NOW(), INTERVAL 1 WEEK), DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), 'Malware eliminado, archivos restaurados desde backup nocturno. Se bloqueó el vector de ataque.', 'solucionado', 30, 240, 1, 1, DATE_SUB(NOW(), INTERVAL 8 DAY)),
('TK-2026-0112', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'hardware', 'media', 'Webcam USB no detectada', 'La webcam Logitech C920 no es detectada por Windows. Necesaria para reuniones con clientes.', 'cerrado', 3, 1, DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), 'Se actualizó driver desde Logitech G Hub. Webcam reconocida y funcionando en Teams/Zoom.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 7 DAY)),
('TK-2026-0113', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'acceso', 'media', 'Recuperar archivos eliminados', 'Borré accidentalmente la carpeta "Reportes 2025" de la carpeta compartida.', 'cerrado', 2, 1, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 'Carpeta restaurada desde shadow copy del servidor. Todos los archivos recuperados intactos.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 6 DAY)),
('TK-2026-0114', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'software', 'alta', 'SAP muestra pantalla blanca', 'Al abrir SAP GUI, solo muestra una pantalla blanca. No carga ningún módulo.', 'cerrado', 3, 1, DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY), 'Se reparó la instalación de SAP GUI 7.70 y se limpió la caché local. SAP funcionando.', 'solucionado', 60, 480, 1, 1, DATE_SUB(NOW(), INTERVAL 9 DAY)),
('TK-2026-0115', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'red', 'media', 'Configurar VLAN para IoT portuario', 'Se necesita una VLAN separada para los sensores IoT del sistema de monitoreo del puerto.', 'cerrado', 2, 1, DATE_SUB(NOW(), INTERVAL 3 WEEK), DATE_SUB(NOW(), INTERVAL 3 WEEK), DATE_SUB(NOW(), INTERVAL 3 WEEK), DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 13 DAY), 'VLAN 100 creada y configurada en switches core. 15 sensores IoT migrados y operativos.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 24 DAY)),
('TK-2026-0116', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'software', 'urgente', 'Sistema de facturación caído', 'El sistema de facturación electrónica está completamente caído. No se pueden emitir documentos.', 'cerrado', 3, 1, DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 11 DAY), 'Servicio Apache del servidor de facturación caído por falta de espacio en disco. Logs limpiados y servicio reiniciado.', 'solucionado', 30, 240, 1, 1, DATE_SUB(NOW(), INTERVAL 12 DAY)),
('TK-2026-0117', 6, 'Usuario Demo', 'usuario@puertocoquimbo.cl', 'Operaciones', 'hardware', 'baja', 'Comprar adaptador USB-C a HDMI', 'Mi nuevo laptop solo tiene puertos USB-C y necesito conectar al monitor HDMI.', 'cerrado', 2, 1, DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 9 DAY), 'Adaptador USB-C a HDMI Ugreen comprado e instalado. Video 4K funcionando en monitor externo.', 'solucionado', 240, 2880, 1, 1, DATE_SUB(NOW(), INTERVAL 16 DAY)),
('TK-2026-0118', 7, 'María González', 'maria.gonzalez@puertocoquimbo.cl', 'Administración', 'acceso', 'media', 'Crear buzón compartido en Exchange', 'Se necesita buzón compartido recepcion@puertocoquimbo.cl para el área de recepción.', 'cerrado', 3, 1, DATE_SUB(NOW(), INTERVAL 1 WEEK), DATE_SUB(NOW(), INTERVAL 1 WEEK), DATE_SUB(NOW(), INTERVAL 1 WEEK), DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), 'Buzón recepcion@puertocoquimbo.cl creado en Exchange. Permisos de envío delegados a 3 usuarios.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 9 DAY)),
('TK-2026-0119', 8, 'Carlos Pérez', 'carlos.perez@puertocoquimbo.cl', 'Operaciones', 'otro', 'media', 'Documentar topología de red', 'Solicito documentación actualizada de la topología de red del edificio principal.', 'cerrado', 2, 1, DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 2 WEEK), DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY), 'Diagrama de red actualizado en Visio con todos los switches, APs y servidores. Compartido en carpeta TI.', 'solucionado', 120, 1440, 1, 1, DATE_SUB(NOW(), INTERVAL 16 DAY)),
('TK-2026-0120', 9, 'Ana López', 'ana.lopez@puertocoquimbo.cl', 'Finanzas', 'software', 'alta', 'Corregir formato de facturas PDF', 'Las facturas generadas en PDF tienen el logo desalineado y falta el número de resolución SII.', 'cerrado', 3, 1, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY), 'Se ajustó la plantilla PDF: logo centrado, resolución SII agregada al pie. Facturas emitidas correctamente.', 'solucionado', 60, 480, 1, 1, DATE_SUB(NOW(), INTERVAL 11 DAY));

-- =============================================
-- COMENTARIOS DE EJEMPLO PARA ALGUNOS TICKETS
-- =============================================
INSERT INTO ticket_comments (ticket_id, user_id, user_name, comment, is_internal, is_first_response) VALUES
-- Tickets abiertos
(1, NULL, 'Usuario Demo', 'El error aparece específicamente con archivos Excel de más de 10MB. Adjunto captura de pantalla del error.', 0, 0),
(3, NULL, 'Carlos Pérez', 'Confirmo que afecta a todo el piso. 15 personas sin poder trabajar.', 0, 0),
-- Tickets asignados
(21, 2, 'Soporte TI', 'Recibido. Verificaré si es problema del receptor USB o del mouse.', 0, 1),
(23, 2, 'Soporte TI', 'En camino al muelle 3 con switch de respaldo.', 0, 1),
-- Tickets en proceso
(41, 2, 'Soporte TI', 'Detecté regla incorrecta en el firewall que bloquea puertos 443 y 8443. Corrigiendo.', 0, 1),
(41, 2, 'Soporte TI', 'Verificar con usuario de Finanzas que pueda acceder al SII antes de cerrar.', 1, 0),
(45, 2, 'Soporte TI', 'Hay 3 queries sin índice que generan full table scan. Creando índices.', 1, 1),
-- Tickets pendientes
(61, 2, 'Soporte TI', 'Repuesto confirmado por proveedor HP Chile. Número de seguimiento: HP-2026-45678.', 0, 1),
(63, 2, 'Soporte TI', 'ISP Movistar confirma cuadrilla en terreno. Ticket ISP: MOV-2026-98765.', 0, 1),
(63, 2, 'Soporte TI', 'Mientras tanto activé el enlace de respaldo 4G con 50Mbps. Suficiente para operación básica.', 0, 0),
-- Tickets resueltos
(81, 2, 'Soporte TI', 'Perfil de Outlook corrupto. Creando nuevo perfil MAPI.', 0, 1),
(81, 2, 'Soporte TI', 'Nuevo perfil configurado. Correos sincronizando correctamente.', 0, 0),
(81, 6, 'Usuario Demo', 'Confirmado, ya puedo enviar y recibir correos sin problema. Gracias!', 0, 0),
(83, 2, 'Soporte TI', 'Revisando configuración del switch. Puerto 24 estaba en modo trunk.', 0, 1),
(83, 2, 'Soporte TI', 'Puerto reconfigurado a access mode VLAN 10. Conectividad restaurada.', 0, 0),
-- Tickets cerrados
(101, 2, 'Soporte TI', 'Driver HP Universal descargado. Instalando en equipo del usuario.', 0, 1),
(101, 2, 'Soporte TI', 'Instalación completada. Página de prueba impresa correctamente.', 0, 0),
(101, 6, 'Usuario Demo', 'Imprime perfecto. Pueden cerrar el ticket. Gracias!', 0, 0),
(111, 2, 'Soporte TI', 'ALERTA: Ransomware Lockbit detectado. Aislando servidor de la red inmediatamente.', 1, 1),
(111, 2, 'Soporte TI', 'Servidor aislado. Iniciando restauración desde backup de las 02:00 AM.', 1, 0),
(111, 2, 'Soporte TI', 'Archivos restaurados al 100%. Vector de entrada: email de phishing. Se bloqueó el dominio.', 0, 0);

SELECT CONCAT('Tickets insertados: ', COUNT(*)) AS resultado FROM tickets;
SELECT status, COUNT(*) as cantidad FROM tickets GROUP BY status ORDER BY FIELD(status, 'abierto', 'asignado', 'en_proceso', 'pendiente', 'resuelto', 'cerrado');
